# Configuración de H2
spring.datasource.url=jdbc:h2:mem:marketdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Para que podamos ver la consola de H2 en el navegador
spring.h2.console.enabled=true
# Para ver las consultas SQL que Spring hace por nosotros en la consola
spring.jpa.show-sql=true