# Nombre del microservicio
spring.application.name=ms-proveedores

# Puerto
server.port=8080

# H2 - Base de datos en memoria
spring.datasource.url=jdbc:h2:mem:ms_proveedores
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola web de H2 (para ver los datos en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true